<?php
/**
 * @file
 * Code for the OS2Web Webform downloads feature.
 */

include_once 'os2web_webform_downloads.features.inc';

function os2web_webform_downloads_menu() {
  $items['os2web/dlrequest/%/%'] = array(
      'page callback' => 'os2web_webform_downloads_download_request_page',
      'page arguments' => array(2, 3),
      'access arguments' => array("access content"),
      'type' => MENU_CALLBACK,
      'title' => 'Download',
      );

  return $items;
}

function os2web_webform_downloads_theme($existing, $type, $theme, $path) {
  return array(
    'confirmation_page' => array(
      'variables' => array('name' => NULL, 'last_name' => NULL, 'email' => NULL, 'node' => NULL, 'nid' => NULL, 'files' => NULL ),
      'template' => 'dlrequest',
      )
    );
}

function os2web_webform_downloads_download_request_page($nid, $sid) {
  // Get the submission array
  $submission = webform_menu_submission_load($sid, $nid);

  // Process the submission
  $data = os2web_webform_downloads_process_submission($submission,node_load($nid));

  // Process the data throught the theme layer
  $output = theme("confirmation_page", $data);

  //TODO: Send the mail
//  reg_send_email("confirmation", $data);

  return $output;
}

function os2web_webform_downloads_process_submission(&$submission,$node) {
  if($submission) {
    $data = array(
        'sid' => $submission->sid,
        'name' => $submission->data[1]['value'][0],
        'last_name' => $submission->data[2]['value'][0],
        'email' => $submission->data[3]['value'][0],
        'nid' => $node->nid,
        'node' => $node,
        'files' => render(field_view_field('node',$node,'field_webform_attachment')),
        );

    return $data;
  }
}

function os2web_webform_downloads_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'webform_configure_form':
    error_log("Var: \$form = " . print_r($form, 1));
      // Deny acces to redirection setup
      $form['submission']['redirection']['#access'] = false;
      break;
  }
}

function os2web_webform_downloads_node_presave($node) {
  if (($node->type === 'webform') && ($node->webform['redirect_url'] === "<confirmation>")) {
    $node->webform['redirect_url'] = 'os2web/dlrequest/%nid/%sid';
  }
}
