<?php
/**
 * @file
 * os2web_settings.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function os2web_settings_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'multistep_show_step_numbers';
  $strongarm->value = 1;
  $export['multistep_show_step_numbers'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'multistep_status_publishing';
  $strongarm->value = 'default';
  $export['multistep_status_publishing'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'multistep_status_revisions';
  $strongarm->value = 'default';
  $export['multistep_status_revisions'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'multistep_workflow_mode';
  $strongarm->value = 'free';
  $export['multistep_workflow_mode'] = $strongarm;

  return $export;
}
