<?php
/**
 * @file
 * os2web_settings.features.user_permission.inc
 */

/**
 * Implements hook_user_default_permissions().
 */
function os2web_settings_user_default_permissions() {
//   $permissions = array();
// 
//   // Exported permission: access media backend.
//   $permissions['access media backend'] = array(
//     'name' => 'access media backend',
//     'roles' => array(
//       0 => 'Administrator',
//       1 => 'Editor',
//       2 => 'Webmaster',
//     ),
//     'module' => 'media_browser_plus',
//   );
// 
//   // Exported permission: add media from remote sources.
//   $permissions['add media from remote sources'] = array(
//     'name' => 'add media from remote sources',
//     'roles' => array(
//       0 => 'Administrator',
//       1 => 'Editor',
//       2 => 'Kommunikation',
//       3 => 'Webmaster',
//     ),
//     'module' => 'media_internet',
//   );
// 
//   // Exported permission: administer media.
//   $permissions['administer media'] = array(
//     'name' => 'administer media',
//     'roles' => array(
//       0 => 'Administrator',
//     ),
//     'module' => 'media',
//   );
// 
//   // Exported permission: administer media folders.
//   $permissions['administer media folders'] = array(
//     'name' => 'administer media folders',
//     'roles' => array(
//       0 => 'Administrator',
//       1 => 'Editor',
//       2 => 'Webmaster',
//     ),
//     'module' => 'media_browser_plus',
//   );
// 
//   // Exported permission: download media.
//   $permissions['download media'] = array(
//     'name' => 'download media',
//     'roles' => array(
//       0 => 'Administrator',
//       1 => 'Editor',
//       2 => 'Webmaster',
//     ),
//     'module' => 'media_browser_plus',
//   );
// 
//   // Exported permission: edit media.
//   $permissions['edit media'] = array(
//     'name' => 'edit media',
//     'roles' => array(
//       0 => 'Administrator',
//       1 => 'Editor',
//       2 => 'Webmaster',
//     ),
//     'module' => 'media',
//   );
// 
//   // Exported permission: filter media.
//   $permissions['filter media'] = array(
//     'name' => 'filter media',
//     'roles' => array(
//       0 => 'authenticated user',
//     ),
//     'module' => 'media_browser_plus',
//   );
// 
//   // Exported permission: import media.
//   $permissions['import media'] = array(
//     'name' => 'import media',
//     'roles' => array(
//       0 => 'Administrator',
//       1 => 'Editor',
//       2 => 'Kommunikation',
//       3 => 'Webmaster',
//     ),
//     'module' => 'media',
//   );
// 
//   // Exported permission: media grid view.
//   $permissions['media grid view'] = array(
//     'name' => 'media grid view',
//     'roles' => array(
//       0 => 'authenticated user',
//     ),
//     'module' => 'media_browser_plus',
//   );
// 
//   // Exported permission: media list view.
//   $permissions['media list view'] = array(
//     'name' => 'media list view',
//     'roles' => array(
//       0 => 'authenticated user',
//     ),
//     'module' => 'media_browser_plus',
//   );
// 
//   // Exported permission: preview media.
//   $permissions['preview media'] = array(
//     'name' => 'preview media',
//     'roles' => array(),
//     'module' => 'media_browser_plus',
//   );
// 
//   // Exported permission: upload media.
//   $permissions['upload media'] = array(
//     'name' => 'upload media',
//     'roles' => array(
//       0 => 'authenticated user',
//     ),
//     'module' => 'media_browser_plus',
//   );
// 
//   // Exported permission: view media.
//   $permissions['view media'] = array(
//     'name' => 'view media',
//     'roles' => array(
//       0 => 'Administrator',
//       1 => 'Editor',
//       2 => 'Webmaster',
//     ),
//     'module' => 'media',
//   );
// 
//   return $permissions;
}
