<?php
define('ACADRE_CM_ACCESS_OPEN_DOCUMENT', '3');

/* Field information hooks */

function os2web_doc_field_field_info() {
  return array(
      'doc_ident' => array(
          'label' => t('ESDH Document'),
          'description' => 'Dokument-id skal være på formen nummer/år eller nummer-år. Flere dokumenter skal være adskildt af , (komma).',
          'default_widget' => 'doc_ident_widget',
          'default_formatter' => 'doc_ident_formatter',
      ),
  );
}

function os2web_doc_field_field_formatter_info() {
  return array(
      'doc_ident_formatter' => array(
          'label' => t('ESDH Document includer'),
          'field types' => array('doc_ident'),
      )
  );
}

function os2web_doc_field_field_widget_info() {

  return array(
      'doc_ident_widget' => array(
          'label' => t('Document Identifier'),
          'field types' => array('doc_ident'),
      )
  );
}

/**
 * Field widget form hook
 *
 */
function os2web_doc_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $field_name = $field['field_name'];
  $field_type = $field['type'];
  $default = '';
  if (isset($form_state['node']->{$field_name}[$langcode][$delta][$field_type])) {
    $default = ($form_state['node']->{$field_name}[$langcode][$delta][$field_type])? : 0;
  }
  switch ($instance['widget']['type']) {
    case 'doc_ident_widget':

      $element['doc_ident'] = array(
          '#type' => 'textfield',
          '#title' => $element['#title'],
          '#description' => $element['#description'],
          '#default_value' => $default,
          '#required' => $element['#required'],
          '#weight' => isset($element['#weight']) ? $element['#weight'] : 0,
          '#delta' => $delta,
      );
      break;
  }
  return $element;
}

function os2web_doc_field_field_is_empty($item, $field) {
  if (empty($item['doc_ident'])) {
    return true;
  }
}

function os2web_doc_field_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  foreach ($items as $delta => $item) {
    $docids = explode(',', $item['doc_ident']);
    foreach ($docids as $docid) {
      $docid = trim($docid);
      $valid = preg_match('/^\d{1,20}[-,\/]\d{2}$/', $docid); // Adopt this for further testing
      if (!$valid && ($docid != '')) {
        $errors[$field['field_name']][$langcode][$delta][] = array(
            'error' => 'Ugyldig fremstilling af dokument-id. Dokument-id skal være på formen nummer/år eller nummer-år. Flere dokumenter skal være adskildt af , (komma).',
            'message' => t('%name: illegal value.', array('%name' => $instance['label'])),
        );
      }
    }
  }
}

/**
 * Field formatter hook
 *
 */
function os2web_doc_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'doc_ident_formatter':
      foreach ($items as $delta => $item) {
        if ($item['doc_ident']) {
          $docs = array();
          $ids = explode(',', $item['doc_ident']);
          foreach ($ids as $id) {
            if (!is_numeric($id)) {
              $pws = _os2web_pws_get_instance();
              $docs[] = $pws->lookupDoc(trim($id));
            } else {
              $docs[] = trim($id);
            }
          }
          $element[$delta]['#markup'] = '<div class="documenttable">' . theme('esdh_document', array('id' => $docs)) . '</div>';
        }
      }
      break;
  }
  return $element;
}

function os2web_doc_field_theme() {
  return array(
      'esdh_document' => array(
          'variables' => array('id' => FALSE),
      ),
  );
}

function theme_esdh_document($vars) {
  $id = $vars['id'];
  drupal_load('module', 'os2web_pws');
  drupal_load('module', 'os2web_case_field');
  $pws = _os2web_pws_get_instance();
  if (!is_array($id)) {
    $id = array($id);
  }
  $html = '';
  $rows = array();
  foreach ($id as $docid) {
    $doc = $pws->getDocument($docid);
    if (_os2web_doc_field_doc_access($docid)) { // Only show public documents
      if (isset($doc->Document) && _os2web_case_field_case_access($doc->Record->CaseFileReference)) {
        $rows[] = array(
            l($doc->Document->DocumentTitleText, $pws->getDocData($doc->Document->DocumentIdentifier)) . '<span class="documentdate">' . format_date(strtotime($doc->Record->RecordLatestUpdateDate), 'custom', 'd/m/Y') . '</span>',
        );
      }
    }
  }
  if (count($rows) == 0) {
    if ($vars['iscase']) {
      $html .= '<p>' . t('This case contains no public documents.') . '</p>';
    }
    return $html;
  }
  /* Hack and slash
    if (isset($vars['iscase'])&&$vars['iscase']) {
    $html .= '<p>' . t('This case contains @docs public documents', array('@docs' => count($rows))) . '</p>';
    }
    $html .= theme('table', array('header' => $header, 'rows' => $rows)); */
  $html .= theme('table', array('rows' => $rows));
  return $html;
}

function _os2web_doc_field_doc_access($docid) {
  drupal_load('module', 'os2web_pws');
  $pws = _os2web_pws_get_instance();
  $doc = $pws->getDocument($docid);
  $access_grant = array(
      'accesscode' => 'KK',
      'publication' => ACADRE_CM_ACCESS_OPEN_DOCUMENT,
      'lockstatus' => true,
  );
  $access = array(
      'accesscode' => $doc->Record->AccessCode,
      'publication' => $doc->Record->PublicationIndicator,
      'lockstatus' => $pws->getDocLock($docid),
  );
  return _os2web_doc_field_array_compare($access, $access_grant);
}

function _os2web_doc_field_array_compare(array $a1, array $a2) {
  $result = true;
  foreach ($a1 as $key => $value) {
    if (isset($a2[$key]) && $a2[$key] === $value) {
      $result = $result && true;
    } else {
      $result = $result && false;
    }
  }
  return $result;
}