<?php

define('DEFAULT_ACADRE_IMPORT_DIR', 'public://acadre');

function os2web_meetings_menu() {
  $items = array();
  $items['os2web/test/meetings'] = array(
      'page callback' => 'os2web_meetings_test_page',
      'access arguments' => array('administer os2web'),
      'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_form_alter()
 */
function os2web_meetings_form_os2web_settings_settings_form_alter(&$form, &$form_state) {
  $form['meetings'] = array(
      '#type' => 'fieldset',
      '#title' => 'Referat import',
      '#description' => 'Indstillinger der vedrører importen af Acadre referater og dagsordener.',
      '#tree' => TRUE,
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
  );
  $form['meetings']['os2web_meetings_path'] = array(
      '#type' => 'textfield',
      '#title' => 'Sti til acadre publish folder.',
      '#description' => 'Dette er stien hvor Acadre publisere .XML filer til.',
      '#default_value' => variable_get('os2web_meetings_path', DEFAULT_ACADRE_IMPORT_DIR),
  );
}

function os2web_meetings_test_page() {
  global $debug_info;

  os2web_meetings_do_import();
  os2web_meetings_order_addenums();

  return '<div><textarea cols="150" rows=50>' . print_r($debug_info, 1) . '</textarea>';
}

/**
 * Import xml files from the defined folder
 *
 */
function os2web_meetings_do_import() {
  $options = array(
      'callback' => '_os2web_meetings_process_manifest',
      'recurse' => FALSE,
  );
  file_scan_directory(variable_get('os2web_meetings_path', DEFAULT_ACADRE_IMPORT_DIR), '/\.xml$/i', $options);
}

/**
 * This function will set up the addenum connections for meetings.
 *
 */
function os2web_meetings_order_addenums() {
  // Find all meetings and gather meeting and agenda_ids
  $nodes = entity_load('node', FALSE, array('type' => 'meeting'));
  $meetings = array();
  // meetings as: $meetings[<meeting_id>][<system_id>][<node_id>]
  foreach ($nodes as $node) {
    $meetings[$node->field_meeting_id[$node->language][0]['value']][$node->field_system_id[$node->language][0]['value']] = $node->nid;
  }
  foreach ($meetings as $meeting) {
    ksort($meeting); // Lowest system id first
    $primary = array_shift($meeting); // Lowest system id is primary
    $addenums = array();
    while ($next = array_shift($meeting)) {
      // Set up references for addenum agendas
      $node = $nodes[$next];
      $node->field_addenum_to[$node->language][0]['nid'] = $primary;
      node_save($node);
    }
  }
}

/**
 * Processes a manifest file
 * 
 * @param string $file File URI. Works as callback in file_scan_directory works.
 */
function _os2web_meetings_process_manifest($file) {
  $manifest = simplexml_load_file(drupal_realpath($file));
  $items_xml = $manifest->xpath("//table[@name='producedAgenda']/fields");
  foreach ($items_xml as $xml_item) {
    _os2web_meetings_process_agenda($xml_item);
  }
}

/**
 * Processes an agenda item
 *
 * @param SimpleXMLElement $agendainfo Chunk of XML representing the agenda part.
 */
function _os2web_meetings_process_agenda($agendainfo_xml) {
  $agendainfo = array(
      'sysid' => (int) array_shift($agendainfo_xml->xpath('field/@sysid')),
      'xmlFusionID' => (int) array_shift($agendainfo_xml->xpath('field/@xmlFusionID')),
      'xmlfilename' => (string) array_shift($agendainfo_xml->xpath('field/@xmlfilename')),
      'docID' => (string) array_shift($agendainfo_xml->xpath('field/@docID')),
      'docfilename' => (string) array_shift($agendainfo_xml->xpath('field/@docfilename')),
      'type' => (int) array_shift($agendainfo_xml->xpath('field/@type')),
      'comment' => (string) array_shift($agendainfo_xml->xpath('field/@comment')),
      'fileType' => (string) array_shift($agendainfo_xml->xpath('field/@fileType')),
      'access' => (string) array_shift($agendainfo_xml->xpath('field/@access')),
      'accessid' => (int) array_shift($agendainfo_xml->xpath('field/@accessid')),
      'publish' => (int) array_shift($agendainfo_xml->xpath('field/@publish')),
      'publishDate' => (string) array_shift($agendainfo_xml->xpath('field/@publishDate')),
      'createdDate' => (string) array_shift($agendainfo_xml->xpath('field/@createdDate')),
      'filesfolder' => (string) array_shift($agendainfo_xml->xpath('field/@filesfolder')),
      'casePublish' => (string) array_shift($agendainfo_xml->xpath('field/@casePublish')),
      'startDate' => (string) array_shift($agendainfo_xml->xpath('field/@startDate')),
      'endDate' => (string) array_shift($agendainfo_xml->xpath('field/@endDate'))
  );
  if ($agendainfo['publish'] === 1) {
    $agenda_uri = implode('/', array(variable_get('os2web_meetings_path', DEFAULT_ACADRE_IMPORT_DIR), $agendainfo['filesfolder'], $agendainfo['xmlfilename']));
    if (($agenda_uri = _os2web_meetings_similar_file_exists(drupal_realpath($agenda_uri))) !== FALSE) {
      $agenda_xml = simplexml_load_file(drupal_realpath($agenda_uri));
      _os2web_meetings_publish_meeting($agendainfo, $agenda_xml);
    }
  } else {
    _os2web_meetings_unpublish_meeting($agendainfo);
  }
}

/**
 * Removes a meeting node from the infomation supplied.
 *
 * @return bool Nid og the created node.
 * @param array $info
 */
function _os2web_meetings_unpublish_meeting($info) {
//  error_log(basename(__FILE__) . ':' . __LINE__ . ' Unpublish: $agendainfo = ' . print_r($info, 1));
  //TODO: Look up nid of the meeting
  $aid = $info['sysid'];
  error_log(basename(__FILE__) . ':' . __LINE__ . ' Unpublish requested: $aid = ' . print_r($aid, 1));
  //TODO: Remove attached nodes, buttom-up
  //TODO: Remove node.
}

/**
 * Creates a meeting node from the infomation supplied.
 *
 * @return int Nid of the created node.
 * @param array $info
 * @param array $xml
 */
function _os2web_meetings_publish_meeting($info, $xml) {
  global $debug_info;
  $debug_info = $xml;

  //FIXME: Verify this list!
  $no_publish_committee = array(
//       'Direktionsmøde',
//       'Direktions og afdelingschef møde',
//       'Rådhusmad',
//       'Testudvalg',
//       'Nedlagte udvalg',
  );

  //TODO: Look for previously imported version to update
  // Create meeting node
  // Gather info
  $options = array(
      'title' => (string) array_shift($xml->xpath("//table[@name='meeting']/fields/field[@name='name']")),
      'date' => (string) array_shift($xml->xpath("//table[@name='meeting']/fields/field[@name='date']")),
      'finish' => (string) array_shift($xml->xpath("//table[@name='meeting']/fields/field[@name='finish']")),
      'location' => (string) array_shift($xml->xpath("//table[@name='location']/fields/field[@name='name']")),
      'committee' => (string) array_shift($xml->xpath("//table[@name='committee']/fields/field[@name='name']")),
      'description' => (string) array_shift($xml->xpath("//table[@name='agenda']/fields/field[@name='description']")),
      'cdate' => strtotime((string) array_shift($xml->xpath("//table[@name='agenda']/fields/field[@name='producedate']"))),
      'meeting_id' => (string) array_shift($xml->xpath("//table[@name='meeting']/fields/field[@name='sysid']")),
      'id' => $info['sysid'],
  );
  if (in_array($options['committee'], $no_publish_committee)) {
    return;
  }


  //FIXME: Refactor dupe-check to seperate function.
  $nid = db_select('os2web_meetings_imported', 'mi')
      ->fields('mi')
      ->condition('aid', $options['id'])
      ->execute()
      ->fetchObject();
  if (isset($nid->nid) && $nid->nid > 0) {
    node_delete($nid->nid);
  }

  $node = new stdClass(); // We create a new node object
  $node->type = "meeting"; // Or any other content type you want
  $node->language = LANGUAGE_NONE; // Or any language code if Locale module is enabled. More on this below *
  $node->uid = 1; // Or any id you wish

  $node->title = $options['title'];
  $node->path = array('alias' => 'agenda/' . $options['id']); // Setting a node path
  node_object_prepare($node); // Set some default values.

  $node->created = $options['cdate'];
  // Let's add standard body field
  $node->field_meeting_abbr[$node->language][0]['value'] = $options['description'];
  $node->field_meeting_abbr[$node->language][0]['format'] = 'filtered_html'; // If field has a format, you need to define it. Here we define a default filtered_html format for a body field
  // The date
  $node->field_date[$node->language][0]['value'] = $options['date'];
  $node->field_date[$node->language][0]['value2'] = $options['finish'];
  $node->field_date[$node->language][0]['timezone'] = 'Europe/Berlin';
  $node->field_date[$node->language][0]['timezone_db'] = 'UTC';
  $node->field_date[$node->language][0]['date_type'] = 'datetime';
  // Proper id tagging
  $node->field_meeting_id[$node->language][0]['value'] = $options['meeting_id'];
  $node->field_system_id[$node->language][0]['value'] = $options['id'];
  // Make sure the committee term is created and get the term.
  $committee_term = _os2web_meetings_import_committee(array_shift($xml->xpath("//table[@name='committee']")));
  $node->field_committee[LANGUAGE_NONE][0]['tid'] = $committee_term->tid;
  $location_term = _os2web_meetings_import_location(array_shift($xml->xpath("//table[@name='meeting']")));
  $node->field_location[LANGUAGE_NONE][0]['tid'] = $location_term->tid;


//   $movie_id = _os2web_qbrick_get_movie_id($node);
//   if ($movie_id != FALSE) {
//     $info['movie_id'] = $movie_id;
//     $info['movie_chapters'] = _os2web_qbrick_get_chapters($movie_id);
//     $node->field_qbrick_ref[$node->language][0]['id'] = $movie_id;
//     $node->field_qbrick_ref[$node->language][0]['seek'] = 0;
//   } else {
//     $node->field_qbrick_ref = array();
//   }


  //Add nodes for each bullet
//  $items = $xml->xpath("//table[@name='agendaitem']");
  $items = $xml->xpath("//table[@name='agendaitemparents']");
  $item_nids = array();
  foreach ($items as $item) {
    $xml = array_shift($item->xpath("table[@name='agendaitem']"));
    $id = (int) array_shift($item->xpath("fields/field[@name='sort']"));
    $item_nids[] = _os2web_meetings_add_item($info, $xml, $id);
    // add node for each items
  }

  foreach ($item_nids as $nid) {
    $node->field_ref_bullet_points[$node->language][]['target_id'] = $nid;
  }

  // Add items to meeting node.
  // Save the meeting node.
  node_submit($node);
  node_save($node);
  //TODO: add reference to the os2web_meetings_import table
  $record = array(
      'nid' => $node->nid,
      'aid' => $options['id'],
  );
  drupal_write_record('os2web_meetings_imported', $record);
}

function _os2web_meetings_add_item($info, $xml, $id) {
  $options = array(
      'sysid' => (int) array_shift($xml->xpath("fields/field[@name='sysid']")),
      'name' => (string) array_shift($xml->xpath("fields/field[@name='name']")),
      'accessname' => (string) array_shift($xml->xpath("fields/field[@name='accessname']")),
  );


  // Gather the bullets for the item
  $bullets = $xml->xpath("table[@name='bullet']");
  $nids = array();
  foreach ($bullets as $bullet) {
//    $bullet_id = (int) array_shift($bullet->xpath("fields/field[@name='sysid']"));
    // Add node for each bullet
    $nids[] = _os2web_meetings_add_bullet($bullet);
  }
  $node = new stdClass();
  $node->type = "bullet_point"; // Or any other content type you want
  $node->language = LANGUAGE_NONE; // Or any language code if Locale module is enabled. More on this below *
  $node->uid = 1; // Or any id you wish
  $node->title = 'Punkt ' . $id . ' ' . $options['name'];
  
  node_object_prepare($node); // Set some default values.

  //Stan added chech for closed bullet point
  if (strcmp($options['accessname'],'Lukket') == 0){
    $node->field_bul_point_closed[$node->language][0]['value'] = 1;
    print_r($node);
    print_r('<br/>');
  }
  else {
    $node->field_bul_point_closed[$node->language][0]['value'] = 0;
  }
  //

//   if (isset($info['movie_id']) && is_numeric($info['movie_chapters'][$id])) {
//     $node->field_qbrick_ref[$node->language][0]['id'] = $info['movie_id'];
//     $node->field_qbrick_ref[$node->language][0]['seek'] = $info['movie_chapters'][$id];
//   }

  foreach ($nids as $nid) {
    $node->field_ref_attachment[LANGUAGE_NONE][]['target_id'] = $nid;
  }

  //TODO: Gather enclosures
/*  $enclosures = $xml->xpath("table[@name='enclosure']");
  foreach ($enclosures as $enclosure) {
    $filename = (string) array_shift($enclosure->xpath("fields/field[@name='filename']"));
    $uri = implode('/', array(variable_get('os2web_meetings_path', DEFAULT_ACADRE_IMPORT_DIR), $info['filesfolder'], $filename));

    $fid = db_select('file_managed', 'fm')
            ->fields('fm', array('fid'))
            ->condition('uri', $uri)
            ->execute()->fetchField();

    $file = new stdClass();
    if ($fid) {
      $file->fid = $fid;
    }
    $file->uri = $uri;
    $file->display = 1;
    $file->filename = drupal_basename($file->uri);
    $file->filemime = file_get_mimetype($file->uri);
    $file->uid = 1;
    $file->status = FILE_STATUS_PERMANENT;
    $file = file_save($file);

    $node->field_enclosures[$node->language][] = (array) $file;
  }*/
  node_submit($node);
  node_save($node);

  return $node->nid;
}

/**
 * Creates a bullet node from xml input
 *
 * @param SimpleXMLElement $xml
 * @return int - Node ID
 */
function _os2web_meetings_add_bullet(SimpleXMLElement $xml) {

  $options = array(
      'sysid' => (int) array_shift($xml->xpath("fields/field[@name='sysid']")),
      'name' => (string) array_shift($xml->xpath("fields/field[@name='bulletname']")),
      'content' => (string) array_shift($xml->xpath("fields/field[@name='bulletcontent']")),
      'type' => (int) array_shift($xml->xpath("fields/field[@name='bullettype']")),
      'weight' => (int) array_shift($xml->xpath("fields/field[@name='bulletsortorder']")),
      'lastbullet' => (int) array_shift($xml->xpath("fields/field[@name='lastbullet']")),
  );
  $node = new stdClass();
  $node->type = "bullet_point_attachment"; // Or any other content type you want
  $node->language = LANGUAGE_NONE; // Or any language code if Locale module is enabled. More on this below *
  $node->uid = 1; // Or any id you wish

  $node->title = $options['name'];

  node_object_prepare($node); // Set some default values.
  // Let's add standard body field
  $node->field_bpa_body[$node->language][0]['value'] = $options['content'];
  $node->field_bpa_body[$node->language][0]['format'] = 'filtered_html'; // If field has a format, you need to define it. Here we define a default filtered_html format for a body field
//  $node->field_weight[LANGUAGE_NONE][0]['value'] = $options['weight'];

  node_submit($node);
  node_save($node);

  return $node->nid;
}

/**
 * Processes xml for committee and creates terms as needed.
 *
 * @param SimpleXMLElement $xml
 * @return \stdClass 
 */
function _os2web_meetings_import_committee(SimpleXMLElement $xml) {
  //TODO: Process members of the committee.
  //FIXME: MAke vocab name configurable.
  $vid = db_select('taxonomy_vocabulary', 'tv')
      ->fields('tv', array('vid'))
      ->condition('machine_name', 'committee')
      ->execute()
      ->fetchField();

  $term = new stdClass();
  $term->vid = $vid;
  $term->name = (string) array_shift($xml->xpath("fields/field[@name='name']"));
  $term->description = (string) array_shift($xml->xpath("fields/field[@name='description']"));
  $term->field_department_id[LANGUAGE_NONE][0]['value'] = (int) array_shift($xml->xpath("fields/field[@name='deptid']"));
  $term->field_department_name[LANGUAGE_NONE][0]['value'] = (string) array_shift($xml->xpath("fields/field[@name='departmentName']"));

  $tid = db_select('taxonomy_term_data', 'td')
          ->fields('td', array('tid'))
          ->condition('name', $term->name)
          ->condition('vid', $term->vid)
          ->execute()->fetchObject();

  if (isset($tid->tid) && $tid->tid > 0) {
    $term->tid = (int) $tid->tid;
  }
  taxonomy_term_save($term);

  return $term;
}

/**
 * Processes xml for location and creates terms as needed.
 *
 * @param SimpleXMLElement $xml
 * @return \stdClass
 */
function _os2web_meetings_import_location(SimpleXMLElement $xml) {
  //TODO: Process members of the committee.
  //FIXME: MAke vocab name configurable.
  $vid = db_select('taxonomy_vocabulary', 'tv')
      ->fields('tv', array('vid'))
      ->condition('machine_name', 'lokation')
      ->execute()
      ->fetchField();

  $term = new stdClass();
  $term->vid = $vid;
  $term->name = (string) array_shift($xml->xpath("fields/field[@name='location']"));
  $term->description = (string) array_shift($xml->xpath("fields/field[@name='address']"));

  $tid = db_select('taxonomy_term_data', 'td')
          ->fields('td', array('tid'))
          ->condition('name', $term->name)
          ->condition('vid', $term->vid)
          ->execute()->fetchObject();

  if (isset($tid->tid) && $tid->tid > 0) {
    $term->tid = (int) $tid->tid;
  }
  taxonomy_term_save($term);

  error_log(basename(__FILE__) . ':' . __LINE__ . ' Var: $term = ' . print_r($term, 1));
  return $term;
}

/**
 * Case insensitive fileexists(). Code from comments on php.net
 *
 * @param string $filename
 * @return mixed Flase if file not found, case corrected filename if found.
 */
function _os2web_meetings_similar_file_exists($filename) {
  if (file_exists($filename)) {
    return $filename;
  }
  $dir = dirname($filename);
  $files = glob($dir . '/*');
  $lcaseFilename = strtolower($filename);
  foreach ($files as $file) {
    if (strtolower($file) == $lcaseFilename) {
      return $file;
    }
  }
  return false;
}

function os2web_meetings_node_delete($node) {
  if ($node->type === 'meeting') {
    db_delete('os2web_meetings_imported')->condition('nid', $node->nid)->execute();
    //TODO: Delete bullets from meeting.
    foreach ($node->field_ref_bullet_points[$node->language] as $nids) {
      node_delete($nids['target_id']);
    }
  }
  if ($node->type === 'bullet_point') {
    //TODO: Delete bullet attachments from meeting.
    if (isset($node->field_ref_attachment[$node->language])) {
      foreach ($node->field_ref_attachment[$node->language] as $nids) {
        node_delete($nids['target_id']);
      }
    }
    if (isset($node->field_enclosures[$node->language])) {
      foreach ($node->field_enclosures[$node->language] as $file) {
//      file_delete((object) $file, true);
      }
    }
  }
}
