<?php

function os2web_ical_meetings_export_menu() {
    $items = array();

    $items['meetings-export/month/%'] = array(
        'type' => MENU_CALLBACK,
        'page callback' => '_os2web_ical_meetings_export_month_callback',
        'access arguments' => array('access content'),
        'page arguments' => array(2)
    );

    $items['meetings-export/day/%'] = array(
        'type' => MENU_CALLBACK,
        'page callback' => '_os2web_ical_meetings_export_day_callback',
        'access arguments' => array('access content'),
        'page arguments' => array(2)
    );

    return $items;
}

function _os2web_ical_meetings_export_month_callback($date) {
    $date = explode('-', $date);
    if (count($date) != 2) {
        drupal_access_denied();
    }
    $year = $date[0];
    $month = $date[1];

    $date_start = date('Y-m-d', strtotime($year . '-' . $month . '-1'));
    $date_end = date('Y-m-t', strtotime($year . '-' . $month . '-1'));

    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
            ->fieldCondition('field_date', 'value', $date_start, '>=')
            ->fieldCondition('field_date', 'value', $date_end, '<=');

    $result = $query->execute();
    $nids = array_keys($result['node']);
    $meetings = node_load_multiple($nids);
    _os2web_ical_meetings_export_make_ical($meetings);
}

function _os2web_ical_meetings_export_day_callback($date) {
    $date = explode('-', $date);
    if (count($date) != 3) {
        drupal_access_denied();
    }
    $year = $date[0];
    $month = $date[1];
    $day = $date[2];

    $date_start = date('Y-m-d H:i:s', strtotime($year . '-' . $month . '-' . $day . ' 00:00:00'));
    $date_end = date('Y-m-d H:i:s', strtotime($year . '-' . $month . '-' . $day . ' 23:59:59'));

    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
            ->fieldCondition('field_date', 'value', $date_start, '>=')
            ->fieldCondition('field_date', 'value', $date_end, '<=');

    $result = $query->execute();
    $nids = array_keys($result['node']);
    $meetings = node_load_multiple($nids);
    _os2web_ical_meetings_export_make_ical($meetings);
}

function _os2web_ical_meetings_export_make_ical($meetings) {
    global $base_url;
    header('Content-type: application/calendar');
    header('Content-Disposition: attachment; filename="calendar_export.ics"');

    print 'BEGIN:VCALENDAR' . PHP_EOL .
            'VERSION:2.0' . PHP_EOL .
            'METHOD:PUBLISH' . PHP_EOL .
            'X-WR-CALNAME;VALUE=TEXT:WebApp Politik: Kalendar' . PHP_EOL .
            'PRODID:-//Drupal iCal API//EN' . PHP_EOL;

    foreach ($meetings as $meeting) {
        $start_date = date('Ymd\THis\Z', strtotime($meeting->field_date['und'][0]['value']));
        $end_date = date('Ymd\THis\Z', strtotime($meeting->field_date['und'][0]['value2']));

        print 'BEGIN:VEVENT' . PHP_EOL .
                'UID:meeting_' . $meeting->field_meeting_id['und'][0]['value'] . PHP_EOL .
                'SUMMARY:' . $meeting->title . PHP_EOL .
                'DTSTAMP:' . $start_date . PHP_EOL .
                'DTSTART:' . $start_date . PHP_EOL .
                'DTEND:' . $end_date . PHP_EOL .
                'URL;VALUE=URI:' . $base_url . '?q=meeting/' . $meeting->nid . PHP_EOL .
                'DESCRIPTION:' . 'Udvalg: ' . taxonomy_term_load($meeting->field_committee['und'][0]['tid'])->name .
                ' Lokation: ' . taxonomy_term_load($meeting->field_location['und'][0]['tid'])->name . PHP_EOL .
                'END:VEVENT' . PHP_EOL;
    }
    print 'END:VCALENDAR' . PHP_EOL;
}