<?php

/* Field information hooks */

function os2web_case_field_field_info() {
  return array(
      'case_ident' => array(
          'label' => t('ESDH Case'),
          'description' => t('Case identifer.'),
          'default_widget' => 'case_ident_widget',
          'default_formatter' => 'case_ident_formatter',
      ),
  );
}

function os2web_case_field_field_formatter_info() {
  return array(
      'case_ident_formatter' => array(
          'label' => t('ESDH Case includer'),
          'field types' => array('case_ident'),
      )
  );
}

function os2web_case_field_field_widget_info() {

  return array(
      'case_ident_widget' => array(
          'label' => t('Case Identifier'),
          'field types' => array('case_ident'),
      )
  );
}

/**
 * Field widget form hook
 *
 */
function os2web_case_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $field_name = $field['field_name'];
  $field_type = $field['type'];
  $default = '';
  if (isset($form_state['node'])) {
    $default = ($form_state['node']->{$field_name}[$langcode][$delta][$field_type])? : 0;
  }
  switch ($instance['widget']['type']) {
    case 'case_ident_widget':

      $element['case_ident'] = array(
          '#type' => 'textfield',
          '#title' => $element['#title'],
          '#description' => $element['#description'],
          '#default_value' => $default,
          '#required' => $element['#required'],
          '#weight' => isset($element['#weight']) ? $element['#weight'] : 0,
          '#delta' => $delta,
      );
      break;
  }
  return $element;
}

function os2web_case_field_field_is_empty($item, $field) {
  if (empty($item['case_ident'])) {
    return true;
  }
}

/**
 * Field formatter hook
 *
 */
function os2web_case_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'case_ident_formatter':
      foreach ($items as $delta => $item) {
        if ($item['case_ident']) {
          $id = $item['case_ident'];
          if (!is_numeric($id)) {
            $pws = _os2web_pws_get_instance();
            $id = $pws->lookupCase($id);
          }
          $element[$delta]['#markup'] = '<div class="fullcaserender">' . theme('esdh_case',array('id' => $id)) . '</div>';
        }
      }
      break;
  }
  return $element;
}

