<?php
/**
 * Implements hook_menu_minipanels_styles();
 * Adds extra style selection for minipanel
 */
function os2web_special_menu_minipanels_styles() {
  $styles = array(
    'cmstheme' => t('CMSTheme'),
  );
  return $styles;
}


/**
 * Implements javascript
 */
function os2web_special_menu_minipanels_style($menu_config) {
  // 
  drupal_add_js(drupal_get_path('module', 'os2web_special') . '/menu_style.js', array('scope' => 'footer', 'weight' => 100));
  /* Ekstra til søge-felt */
  drupal_add_js(drupal_get_path('module', 'os2web_special') . '/search.js', array('scope' => 'header', 'weight' => 100));
/* Styling af select's bruges måske senere
  drupal_add_js(drupal_get_path('module', 'os2web_special') . '/jquery.yaselect.min.js', array('scope' => 'header', 'weight' => 102));

  drupal_add_js('jQuery(#edit-jump--2).yaselect();', array('type' => 'inline', 'scope' => 'footer', 'weight' => 5));
*/
}


/**
 * Implements hook_search_api_ajax_settings().
 */
function os2web_special_search_api_ajax_settings() {
  $settings = array(
  
    // required: CSS ID for the main content (search results html)
    'content' => '#content .content',
    
    // required: array of regions with search-related blocks => CSS ID's
    'regions' => array(
      'my_region' => '#my-css-id',
      'sidebar_first' => '#sidebar-first',
      'sidebar_second' => '#sidebar-second',
    ),
    
    // optional: if you want to show a spinner image on AJAX
    'spinner' => drupal_get_path('module', 'search_api_ajax') .'/spinner.gif',
    
    // optional: if you want to scroll-back-to-top on paging search results
    'scrolltarget' => '#main-content',
    'scrollspeed' => 1000,
    
    // optional: fade main content on AJAX (fade=1 for true)
    'fade' => 1,
    'opacity' => 0.3,    
  );
  
  return $settings;
}
