<?php
/**
 * Implements hook_menu_minipanels_styles().
 */
function menu_style_menu_minipanels_styles() {
  $styles = array(
    'cmstheme' => t('CMSTheme'),
  );
  return $styles;
}
?>


<?php
/**
 * Implements hook_menu_minipanels_style().
 */
function menu_style_menu_minipanels_style($menu_config) {
  // Load the custom styles in the footer but after other things have loaded.
  drupal_add_js(drupal_get_path('module', 'menu_style') . '/menu_style.js', array('scope' => 'footer', 'weight' => 100));
}
?>

<?php
/**
 * Implements hook_search_api_ajax_settings().
 */
function mymodule_search_api_ajax_settings() {
  $settings = array(
  
    // required: CSS ID for the main content (search results html)
    'content' => '#content .content',
    
    // required: array of regions with search-related blocks => CSS ID's
    'regions' => array(
      'my_region' => '#my-css-id',
      'sidebar_first' => '#sidebar-first',
      'sidebar_second' => '#sidebar-second',
    ),
    
    // optional: if you want to show a spinner image on AJAX
    'spinner' => drupal_get_path('module', 'search_api_ajax') .'/spinner.gif',
    
    // optional: if you want to scroll-back-to-top on paging search results
    'scrolltarget' => '#main-content',
    'scrollspeed' => 1000,
    
    // optional: fade main content on AJAX (fade=1 for true)
    'fade' => 1,
    'opacity' => 0.3,    
  );
  
  return $settings;
}
?>

<?php
/* Ekstra til søge-felt */


function menu_style_menu_minipanels_style($menu_config) {
  // Load the custom styles in the footer but after other things have loaded.
  drupal_add_js(drupal_get_path('module', 'menu_style') . '/search.js', array('scope' => 'header', 'weight' => 100));
}

?>
