<?php

define('AVAILABLE_PUBLIC', 3);
define('DEFAULT_DOC_CACHE_PATH', 'public://pws_documents/');

function os2web_pws_menu() {
//  $items['admin/config/os2web/pws'] = array(
//      'title' => 'PWS Setup',
//      'description' => t('Set up endpoints for PWS webservices.'),
//      'page callback' => 'drupal_get_form',
//      'page arguments' => array('os2web_pws_config_form'),
//      'access arguments' => array('administer os2web'),
//      'file' => 'os2web_pws.admin.inc',
//      'type' => MENU_NORMAL_ITEM | MENU_LOCAL_TASK,
//  );
  $items['os2web/test/pws'] = array(
      'title' => 'PWS Test',
      'page callback' => 'os2web_test_page',
      'access arguments' => array('administer os2web'),
      'type' => MENU_CALLBACK,
  );
  $items['os2web/showcase/%'] = array(
      'title callback' => 'os2web_pws_case_listing_title',
      'title arguments' => array(2),
      'page callback' => 'os2web_pws_case_listing',
      'page arguments' => array(2),
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
  );
  $items['os2web/showcase/%/%'] = array(
      'title callback' => 'os2web_pws_case_listing_title',
      'title arguments' => array(2, 3),
      'page callback' => 'os2web_pws_case_listing',
      'page arguments' => array(2, 3),
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Add configuration to the settings form
 *
 * @param type $form
 * @param type $form_state
 */
function os2web_pws_form_os2web_settings_settings_form_alter(&$form, &$form_state) {
  $form['os2web_pws_config_group'] = array(
      '#type' => 'fieldset',
      '#title' => t('PWS Endpoint configuration'),
  );
  $form['os2web_pws_config_group']['os2web_pws_url'] = array(
      '#type' => 'textfield',
      '#default_value' => variable_get('os2web_pws_url'),
      '#title' => t('PWS URL for V4'),
      '#description' => t('URL to the PWS webservice endpoint.'),
  );
  $form['os2web_pws_config_group']['os2web_pws_url_v6'] = array(
      '#type' => 'textfield',
      '#default_value' => variable_get('os2web_pws_url_v6'),
      '#title' => t('PWS URL for  V6'),
      '#description' => t('URL to the PWSv6 webservice endpoint.'),
  );
  $form['os2web_pws_config_group']['os2web_pws_url_search'] = array(
      '#type' => 'textfield',
      '#default_value' => variable_get('os2web_pws_url_search'),
      '#title' => t('PWS URL for Search service'),
      '#description' => t('URL to the webservice endpoint that runs the search service.'),
  );
  $form['os2web_pws_config_group']['os2web_pws_user'] = array(
      '#type' => 'textfield',
      '#default_value' => variable_get('os2web_pws_user'),
      '#title' => t('PWS login user'),
      '#description' => t('PWS HTTP authentification user.'),
  );
  $form['os2web_pws_config_group']['os2web_pws_password'] = array(
      '#type' => 'textfield',
      '#default_value' => variable_get('os2web_pws_password'),
      '#title' => t('PWS password'),
      '#description' => t('PWS HTTP authentification password.'),
  );
  $form['os2web_pws_adlib_group'] = array(
      '#type' => 'fieldset',
      '#title' => t('Adlib Endpoint configuration'),
  );
  $form['os2web_pws_adlib_group']['os2web_adlib_url'] = array(
      '#type' => 'textfield',
      '#default_value' => variable_get('os2web_adlib_url','http://706CAR01/ExponentWSA/ExponentWSA.asmx?wsdl'),
      '#title' => t('URL for Adlib service endpoint'),
      '#description' => t('URL to the webservice endpoint that runs the Adlib service.'),
  );
}

/**
 * Factory for class instances. This allows easy changing between api classes.
 * TODO: Make this proper plugin-able.
 *
 * @return AcadrePWS object
 */
function _os2web_pws_get_instance() {
  module_load_include('inc', 'os2web_pws', 'AcadrePWS.class');
  return new AcadrePWS();
//  module_load_include('inc', 'os2web_pws', 'AcadrePWSMock.class');
//  return new AcadrePWSMock();
}

/**
 * Factory for class instances. This allows easy changing between api classes.
 * TODO: Make this proper plugin-able.
 *
 * @return AdLibWS object
 */
function _os2web_adlib_get_instance() {
  module_load_include('inc', 'os2web_pws', 'AdLibWS.class');
  return new AdLibWS();
//  module_load_include('inc', 'os2web_pws', 'AcadrePWSMock.class');
//  return new AcadrePWSMock();
}

function os2web_pws_case_listing_title($id, $id2 = false) {
  $case = &drupal_static('os2web_pws_case', FALSE);
  if (FALSE === $case) {
    $pws = _os2web_pws_get_instance();
    if (FALSE != $id2) {
      $id = $pws->lookupCase($id . "/" . $id2);
    }
    $case = $pws->fetchCase($id);
  }
  if (FALSE != $case) {
    return t('Show case: @caseid - @titletext', array('@caseid' => $case->CaseFileNumberIdentifier, '@titletext' => $case->CaseFileTitleText));
  } else {
    return t('Case not found');
  }
}

function os2web_pws_case_listing($id, $id2 = false) {
  $pws = _os2web_pws_get_instance();
//  error_log(basename(__FILE__) . ':' . __LINE__ . ' Var: $id = ' . print_r($id, 1));
//  error_log(basename(__FILE__) . ':' . __LINE__ . ' Var: $id2 = ' . print_r($id2, 1));
  if (FALSE != $id2) {
    $id = $pws->lookupCase($id . "/" . $id2);
  }
  $output = theme('esdh_case', array('id' => $id));
  if (FALSE != $output) {
    return $output;
  } else {
    drupal_not_found();
  }
}

function os2web_test_page() {
  error_log('MARK - ' . basename(__FILE__) . ':' . __LINE__ . ' in ' . __FUNCTION__ . '()');
  $pws = _os2web_pws_get_instance();
//  $adlib = _os2web_adlib_get_instance();
//  $call = $pws->lookupCase('11/14293');
//  $call = $pws->fetchCase($pws->lookupCase('11/4949'));
//  $call = $pws->getCaseDocs($pws->lookupCase('11/4949'));
//  $call = array($pws->getCaseDocs('388538'),$pws->getCaseDocs('388531'));
//  $call = $pws->getCaseDocs($pws->lookupCase('12/6202'));
//  $call = $pws->getCaseDocs($pws->lookupCase('11/14293'));
//  $call = $pws->fetchCase($pws->lookupCase('12/6202'));
//  $call = $pws->getCaseDocs(373830);
  $call = $pws->fetchCase(73335);
//  return _os2web_get_rendered_doc(array(1420175,1369822));
//  $call = $pws->getDocument(1565429);
//  $call = $pws->getCaseDocs($pws->lookupCase('07/4408'));
//  $call = $pws->getCaseDocs(73335);
//  $call = $pws->getDocLock($pws->lookupDoc('268704/07'));
//  $call = $pws->getDocLock(1);
//  $call = $pws->getDocument($pws->lookupDoc('268704/07'));
//  _os2web_pws_cleanup_files();
//  $call = $pws->getDocument(350654);
//  error_log(basename(__FILE__) . ':' . __LINE__ . ' Var: $pws->lookupDoc("268704/07") = ' . print_r($pws->lookupDoc("268704/07"), 1));
//  $call = $pws->getDocFileName(3023484,1);
//  $call = $pws->getDocFileName(1565429);
//  $call = $pws->getDocFileName(3258320,1);
//  $call = $pws->getDocData(3258320, 1);
//  $call = $pws->getDocData(1565429);
//  $call = $pws->getDocDataRaw(1428287);
//  $call = $adlib->uploadData('test.txt', 'test');
//  error_log(basename(__FILE__) . ':' . __LINE__ . ' Var: $call = ' . print_r($call, 1));
//  $call = $adlib->addJob($call);
//  $call = '162749a4-c4ac-4119-bdf8-5ba561fbfb0b\311';
//  $call = $adlib->getJobStatus($call);
//  $call = $adlib->__getFunctions();
//  $call = 'test';
//
//  $call = $call->ArrayOfDocuments->DocumentOutput;
//  $call = $pws->lookupDoc('4949/11');
//  error_log(var_export($call,1));
//  foreach ($call as $item) {
//    error_log(basename(__FILE__) . ':' . __LINE__ . ' Var: $item = ' . print_r($item, 1));
//  }
//  return 'test';
//  return theme('esdh_case', array('id' => 349566));
//  echo '<pre>';print_r($call);die;

//  module_load_include('inc', 'os2web_pws','os2web_pws.theme');
//  $a1 = array(
//      'test' => 1,
//  );
//  $a2 = array(
//      'test' => 1,
//  );
//  if (_os2web_pws_array_compare($a1, $a2)) {
//    $call = 'success!';
//  } else {
//    $call = 'fail';
//  }

  return '<div><textarea cols="150" rows=50>' . print_r($call, 1) . '</textarea>
    <textarea cols="150" rows=20>' . print_r($pws->getTrace(), 1) . '</textarea></div>';
}
