<?php


function os2web_webform_confirm_menu() {
  $items['os2web/dlrequest/%/%'] = array(
      'page callback' => 'os2web_webform_confirm_download_request_page',
      'page arguments' => array(2, 3),
      'access arguments' => array("access content"),
      'type' => MENU_CALLBACK,
      'title' => 'Download',
      );

  return $items;
}

function os2web_webform_confirm_theme($existing, $type, $theme, $path) {
  return array(
    'confirmation_page' => array(
      'variables' => array('name' => NULL, 'last_name' => NULL, 'email' => NULL, 'node' => NULL, 'nid' => NULL, 'filename' => NULL, 'fileurl' => NULL),
      'template' => 'dlrequest',
      )
    );
}

function os2web_webform_confirm_download_request_page($nid, $sid) {
  // Get the submission array
  $submission = webform_menu_submission_load($sid, $nid);

  // Process the submission
  $data = os2web_webform_confirm_process_submission($submission,node_load($nid));

  // Process the data throught the theme layer
  $output = theme("confirmation_page", $data);

  // Send the mail
//  reg_send_email("confirmation", $data);

  return $output;
}

function os2web_webform_confirm_process_submission(&$submission,$node) {
  if($submission) {
    $file = array_pop(field_get_items('node',$node,'field_webform_attachment'));
    $data = array(
        'sid' => $submission->sid,
        'name' => $submission->data[1]['value'][0],
        'last_name' => $submission->data[2]['value'][0],
        'email' => $submission->data[3]['value'][0],
        'nid' => $node->nid,
        'node' => $node,
        'filename' => $file['filename'],
        'fileurl' => file_create_url($file['uri']),
        );

    return $data;
  }
}
